# Generated by Django 3.0.4 on 2020-03-06 11:37

from django.db import migrations, models
import film.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('second_name', models.CharField(max_length=200, null=True)),
                ('birthday', models.DateField()),
                ('movies', models.CharField(blank=True, max_length=300, null=True)),
                ('category', models.CharField(max_length=200)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='photos/actors')),
            ],
        ),
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('second_name', models.CharField(max_length=200, null=True)),
                ('birthday', models.DateField()),
                ('movies', models.CharField(blank=True, max_length=300, null=True)),
                ('category', models.CharField(max_length=200)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='photos/directors')),
            ],
        ),
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_film', models.CharField(max_length=300, unique_for_date=True)),
                ('date_premiere', models.DateField()),
                ('genre', models.CharField(max_length=100, unique=True)),
                ('time', models.IntegerField(blank=True, null=True)),
                ('actor', models.CharField(max_length=200, verbose_name=film.models.Actor)),
                ('rating_age', models.IntegerField()),
                ('poster', models.ImageField(blank=True, null=True, upload_to='posters')),
                ('review', models.CharField(blank=True, max_length=200, null=True, verbose_name=film.models.Review)),
                ('is_active', models.BooleanField(default=True)),
                ('actor_dubbing', models.CharField(max_length=200, verbose_name=film.models.Actor)),
                ('comment', models.TextField(max_length=200)),
                ('director', models.CharField(max_length=200, verbose_name=film.models.Director)),
                ('news', models.CharField(max_length=100, verbose_name=film.models.News)),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('head', models.CharField(max_length=100)),
                ('text_news', models.TextField(max_length=500)),
                ('image', models.ImageField(upload_to='news')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.TextField(max_length=200)),
                ('rating', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
